### ISSUE TITLE
Visible

### ISSUE THREAD

**Issue by debjr** [Knetus56/healthbox#3]
Dans la dernière version, toute les commandes sont crées avec setIsVisible(0);

C'est mieux de les afficher en standard

**Comment by Knetus56** [comment]
c"est une question de goût.
________________________________
De : debjr ***@***.***>
Envoyé : lundi 20 février 2023 15:12
À : Knetus56/healthbox ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [Knetus56/healthbox] Visible (Issue #3)


Dans la dernière version, toute les commandes sont crées avec setIsVisible(0);

C'est mieux de les afficher en standard
